version: '3.8'

services:
  backend:
    image: benphil/yt-summarizer-backend:latest
    container_name: yt-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    image: benphil/yt-summarizer-frontend:latest
    container_name: yt-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
      - RUNNING_IN_DOCKER=true
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


# version: '3.8'

# services:
#   backend:
#     build:
#       context: .
#       dockerfile: backend/Dockerfile
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env

#   frontend:
#     build:
#       context: .
#       dockerfile: frontend/Dockerfile
#     ports:
#       - "8501:8501"
#     environment:
#       - BACKEND_URL="http://backend:8000"
#       - RUNNING_IN_DOCKER=true
#     env_file:
#       - .env